export function prBody({ issue, triage, patch, changedFiles, testResult }) {
  const changed = changedFiles.map((path) => `- \`${path}\``).join("\n");
  const rationale = triage.rationale.map((item) => `- ${item}`).join("\n");
  return [
    "## Autonomous GitHub CTO Fix",
    "",
    `Closes #${issue.number}.`,
    "",
    "### Triage",
    `- Severity: **${triage.severity}**`,
    `- Priority score: **${triage.score}/100**`,
    `- Intent: **${triage.intent.kind}**`,
    `- Recommended action: ${triage.recommendedAction}`,
    "",
    "### Rationale",
    rationale,
    "",
    "### Summary",
    patch.summary,
    "",
    "### Changed Files",
    changed || "- No files changed",
    "",
    "### Test Plan",
    patch.testPlan,
    "",
    "### Automation Test Result",
    testResult.command ? `- Command: \`${testResult.command}\`` : "- Command: not configured",
    `- Status: **${testResult.status}**`,
    "",
    "_Generated by GitHub CTO No-Python._",
  ].join("\n");
}

export function issueComment({ triage, pr, changedFiles, testResult }) {
  return [
    "GitHub CTO created a Codex-native PR.",
    "",
    `- Severity: **${triage.severity}** (${triage.score}/100)`,
    `- Intent: **${triage.intent.kind}**`,
    `- PR: ${pr.html_url}`,
    `- Changed files: ${changedFiles.map((path) => `\`${path}\``).join(", ") || "none"}`,
    `- Tests: **${testResult.status}**${testResult.command ? ` via \`${testResult.command}\`` : ""}`,
  ].join("\n");
}

export function failureComment(error) {
  return [
    "GitHub CTO could not complete this issue run.",
    "",
    "```text",
    String(error?.stack || error?.message || error).slice(0, 3000),
    "```",
  ].join("\n");
}
